# Generated by Django 4.1.7 on 2024-07-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0003_problems_examples_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.CharField(max_length=255)),
                ('output', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='problems',
            name='constraints',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='problems',
            name='examples',
        ),
        migrations.AddField(
            model_name='problems',
            name='examples',
            field=models.ManyToManyField(to='oj.examples'),
        ),
    ]
