# Generated by Django 4.1.7 on 2024-07-08 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0004_examples_alter_problems_constraints_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='examples',
        ),
        migrations.DeleteModel(
            name='Examples',
        ),
    ]
