# Generated by Django 4.1.7 on 2024-07-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0005_remove_problems_examples_delete_examples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='difficulty_levels',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'hard')], default='easy', max_length=6),
        ),
    ]
