# Generated by Django 4.1.7 on 2024-07-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oj', '0006_alter_problems_difficulty_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='solved_problems',
            field=models.ManyToManyField(to='oj.problems'),
        ),
    ]
